server:
  port: 8081

jwt:
  issuer: snowball
  subject: auth
  expires-time: 3600
  secret: secretInfo

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/graduate_membership
    username: graduate_membership
    password: 909012
  redis:
    host: localhost
    port: 6379
    password: 909012
